const fs = require('fs');
const path = require('path');

function loadFixture(fixtureName) {
  return JSON.parse(fs.readFileSync(
    path.join(__dirname, `fixtures/${fixtureName}.json`),
    'UTF8',
  ));
}

module.exports = {
  album_full_object: loadFixture('album_full_object'),
  album_is_liked: loadFixture('album_is_liked'),
  album_simple: loadFixture('album_simple'),
  album_tracks: loadFixture('album_tracks'),
  artist_albums: loadFixture('artist_albums'),
  artist_full_object: loadFixture('artist_full_object'),
  artist_is_followed: loadFixture('artist_is_followed'),
  artist_simple: loadFixture('artist_simple'),
  artist_top_tracks: loadFixture('artist_top_tracks'),
  item_simple: loadFixture('item_simple'),
  items_repeats: loadFixture('items_repeats'),
  items_three: loadFixture('items_three'),
  track_audio_analysis: loadFixture('track_audio_analysis'),
  track_audio_features: loadFixture('track_audio_features'),
  track_full_object: loadFixture('track_full_object'),
  track_is_liked: loadFixture('track_is_liked'),
  track_recommendations: loadFixture('track_recommendations'),
  track_simple: loadFixture('track_simple'),
  // artists: loadFixture('artists'),
  // artist_albums: loadFixture('artist_albums'),
  // artist_albums_limit_2: loadFixture('artist_albums_limit_2'),
  // artist_related_artists: loadFixture('artist_related_artists'),
  // artist_top_tracks: loadFixture('artist_top_tracks'),
  // search: loadFixture('search'),
  // search_album: loadFixture('search_album'),
  // search_artist: loadFixture('search_artist'),
  // search_track: loadFixture('search_track'),
  // search_playlist: loadFixture('search_playlist'),
  // search_show: loadFixture('search_show'),
  // search_episode: loadFixture('search_episode'),
  // user: loadFixture('user'),
  // me: loadFixture('me'),
  // user_playlists: loadFixture('user_playlists'),
  // user_new_playlist: loadFixture('user_new_playlist'),
  // user_saved_tracks: loadFixture('user_saved_tracks'),
  // user_saved_albums: loadFixture('user_saved_albums'),
  // user_saved_shows: loadFixture('user_saved_shows'),
  // user_top_artists: loadFixture('user_top_artists'),
  // user_top_tracks: loadFixture('user_top_tracks'),
  // playlist: loadFixture('playlist'),
  // playlist_tracks: loadFixture('playlist_tracks'),
  // playlist_cover_image: loadFixture('playlist_cover_image'),
  // featured_playlists: loadFixture('featured_playlists'),
  // browse_categories: loadFixture('browse_categories'),
  // category: loadFixture('category'),
  // category_playlists: loadFixture('category_playlists'),
  // new_releases: loadFixture('new_releases'),
  // follow_is_following_users: loadFixture('follow_is_following_users'),
  // follow_is_following_artists: loadFixture('follow_is_following_artists'),
  // follow_are_following_playlist: loadFixture('follow_are_following_playlist'),
  // followed_artists: loadFixture('followed_artists'),
  // recommendations: loadFixture('recommendations'),
  // genre_seeds: loadFixture('genre_seeds'),
  // recently_played_tracks: loadFixture('recently_played_tracks'),
  // available_devices: loadFixture('available_devices'),
  // current_playback: loadFixture('current_playback'),
  // current_playing_track: loadFixture('current_playing_track'),
  // show: loadFixture('show'),
  // shows: loadFixture('shows'),
  // show_episodes: loadFixture('show_episodes'),
  // episode: loadFixture('episode'),
  // episodes: loadFixture('episodes'),
};
